# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  osc_ogcapi_records_models.yaml
#   timestamp: 2026-02-16T15:31:22+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import AnyUrl, Field, RootModel
from transpiler_mate.ogcapi_records.ogcapi_records_models import RecordCommonProperties


class WorkflowProperties(RecordCommonProperties):
    osc_project: Optional[str] = Field(None, alias='osc:project')


class ExperimentProperties(RecordCommonProperties):
    osc_workflow: Optional[AnyUrl] = Field(None, alias='osc:workflow')
    osc_prov_generated_by: Optional[str] = Field(None, alias='osc-prov:generatedBy')
    osc_prov_started_at_time: Optional[datetime] = Field(
        None, alias='osc-prov:startedAtTime'
    )
    osc_prov_ended_at_time: Optional[datetime] = Field(
        None, alias='osc-prov:endedAtTime'
    )
    osc_prov_generated: Optional[str] = Field(None, alias='osc-prov:generated')
    osc_prov_described_by_workflow: Optional[AnyUrl] = Field(
        None, alias='osc-prov:describedByWorkflow'
    )
